name: nightscout_reporter
description: A web app to generate reports for nightscout data
# version: 1.0.0
# homepage: https://blog.zreptil.de
# author: Andreas.Perlitz <andi@zreptil.de>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: 5.1.0
  angular_components: 0.10.0
  intl: 0.15.7
  crypto: 2.0.6

dev_dependencies:
  build_runner: 1.0.0
  build_web_compilers: 0.4.4+2
  sass_builder: 2.1.2
  intl_translation: 0.17.2
